language: node_js
node_js:
  - 'node'
services:
  - postgresql
before_script:
  - createdb lambdaNotes
  - psql -c "create user kamdu with password '3649631';" -U postgres -d lambdaNotes
  - npx knex migrate:latest --env development
