language: node_js
node_js:
  - 'node'
services:
  - postgresql
before_script:
  - psql -c "create database lambdaNotes;' -U postgres"
  - psql -c "create user kamdu with password '3649631';" -U postgres"
  - npx knex migrate:latest
